# Site settings
title: James Maxson's Blog
description: 'Powershell lover, Windows Sysadmin, and most recently, Devops Engineer. Expect to also see posts about D&D.'
url: 'http://maxfrost.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'https://maxfrost-github-io'

author:
  name: 'James Maxson'
  email: MaximumFrost@gmail.com
  mastodon_username: '@MaxFrost'
  github_username:  MaxFrost
  linkedin_username: james-maxson-36349112

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
